### ISSUE TITLE
Game Crashes when installing Music and SFX folders

### ISSUE THREAD

**Issue by OpenRift412** [Xenoveritas/abuse#20]
If i'm understanding this right, I'm supposed to copy the SFX and MUSIC data folders to the Abuse SDL directory, correct? Whenever I do, the game gets to the loading console screen and then crashes before I can see what's wrong.

Am I missing something here?

**Comment by deviant-syndrome** [comment]
Hello. I think to reliably reproduce the issue, we would need to know, where those SFX and MUSIC files came from? Was it fRAPs, the original Abuse Box distribution, or the shareware files? 
Thank you!

**Comment by OpenRift412** [comment]
> Hello. I think to reliably reproduce the issue, we would need to know, where those SFX and MUSIC files came from? Was it fRAPs, the original Abuse Box distribution, or the shareware files? Thank you!

If I recall correctly it was from the CD distribution, because I took it from my DOS install of the game (not shareware).

**Comment by deviant-syndrome** [comment]
Okay. I think I know, what is causing problems. 
You're running a version of the port, that is still configured to run with the fRABs data, which for some reason has additional graphics and SFX. And abuse.lsp had some references to those, through includes. 
Please, see this change: https://github.com/Xenoveritas/abuse/commit/b14fbb7fde62233989bfa0a737947c76fd35b8bc#diff-2bbd23f09960e5916633e6faa3a107b2a35b4043100e70005f68fd35519ba1ebL40-L50 

So, I think the best way to resolve this issue is to undo those changes (and also changes below) in the `abuse.lsp` file. LSP files in this game are compiled at runtime, and they are human readable/editable. 

If it sounds too tedious to fiddle with, you can probably just substitute `data/abuse.lsp` with the same file from your CD distribution.

Hope that helps. Thank you

**Comment by OpenRift412** [comment]
> Okay. I think I know, what is causing problems. You're running a version of the port, that is still configured to run with the fRABs data, which for some reason has additional graphics and SFX. And `abuse.lsp` had some references to those, through includes. Please, see this change: [Remove fRaBs entirely](https://github.com/Xenoveritas/abuse/commit/b14fbb7fde62233989bfa0a737947c76fd35b8bc#diff-2bbd23f09960e5916633e6faa3a107b2a35b4043100e70005f68fd35519ba1ebL40-L50)
> 
> So, I think the best way to resolve this issue is to undo those changes (and also changes below) in the `abuse.lsp` file. LSP files in this game are compiled at runtime, and they are human readable/editable.
> 
> If it sounds too tedious to fiddle with, you can probably just substitute `data/abuse.lsp` with the same file from your CD distribution.
> 
> Hope that helps. Thank you

I think replacing abluse.lsp seemed to work. Though it's not really contained in .\data\, it's just in the base directory. 

The question at this point is though: why not just have the port include the original LSP from the 2.00 version without the SFX and MUSIC folders? It's freeware anyway, so I'd imagine it wouldn't be a problem to include, right?

**Comment by deviant-syndrome** [comment]
@OpenRift412 , the latest master of this repository, seem to actually, have the original lsp's. The PR I mentioned earlier reverts the modification related to fRaBs extra content. So, the release 0.9 that you presumably downloaded, is a bit outdated. 

The release schedule and related questions are better to be addressed to the original maintainer / repository owner. 
@Xenoveritas , I think this issue can be closed. 

Thank you.

**Comment by shodanx2** [comment]
Hello, 

Having the same issue as the original poster

installed this
https://github.com/Xenoveritas/abuse/releases/tag/v0.9.1

in default location
C:\Program Files (x86)\Abuse 0.9.1

as the release text mentions 
I downloaded
http://abuse.zoy.org/raw-attachment/wiki/download/golgotha-sfx.tar.gz
http://abuse.zoy.org/raw-attachment/wiki/download/golgotha-music.tar.gz

and unpacked in (respectively)
C:\Program Files (x86)\Abuse 0.9.1\music
C:\Program Files (x86)\Abuse 0.9.1\sfx

And the game does not start with this error message

![image](https://github.com/user-attachments/assets/40bc0fc6-f5c5-41da-a8d3-dc9b1a739d46)


`C:\Program Files (x86)\Abuse 0.9.1>abuse
abuse 0.9.1
Setting data dir to C:\Program Files (x86)\Abuse 0.9.1
Abuse version 0.9.1
Sound: Enabled
Specs : main file set to abuse.spe
Protocol Installed : UNIX generic TCPIP
Lisp: 527 symbols defined, 99 system functions, 319 pre-compiled functions
0 joysticks on system
Joystick : not detected
(load "abuse.lsp") [..............                          ]Unable to open file 'sfx/ball01.wav' for reading
warning: cleaning up nonempty stack
`

I tried both user console and admin console, same issue
