### ISSUE TITLE
Please provide binaries

### ISSUE THREAD

**Issue by marcosdiez** [Xenoveritas/abuse#9]
Hi! Could you please provided binaries of a working version for those who don't want the hassle to compile it themselves ? 
Thanks you!

**Comment by Xenoveritas** [comment]
Sorry for the delay on this. I've published a 0.9.0 release that does not include any of the non-free SFX or music. It is possible to get that data from somewhere else and add them, but the current build skips all SFX to the FRABS stuff that's included won't work if you just copy the `sfx` and `music` directories from the non-free version.
